providers = []
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1697500996'

[variables]
NIXPACKS_METADATA = 'staticfile'

[staticAssets]
"nginx.conf" = '''
daemon off;
error_log /dev/stdout info;
worker_processes  auto;
events {
    worker_connections  1024;
}

http {
    include /nix/store/*-user-environment/conf/mime.types;
    access_log /dev/stdout;
    default_type  application/octet-stream;
    sendfile       on;
    keepalive_timeout  60;
    types_hash_max_size 4096;
    server {
        listen    0.0.0.0:80;
        gzip  	  on;
        root	  /app/site;
        location / {

            autoindex off;
        }

    }
}
'''
[phases.setup]
nixPkgs = ['nginx']
nixOverlays = []
nixpkgsArchive = '5148520bfab61f99fd25fb9ff7bfbb50dad3c9db'
cmds = ['mkdir /etc/nginx/ /var/log/nginx/ /var/cache/nginx/']

[start]
cmd = '[[ -z "${PORT}" ]] && echo "Environment variable PORT not found. Using PORT 80" || sed -i "s/0.0.0.0:80/$PORT/g" /assets/nginx.conf && nginx -c /assets/nginx.conf'